### ISSUE TITLE
Error when creating volume using -v

### ISSUE THREAD

**Issue by chetan-70** [AdminTurnedDevOps/100DaysOfContainersAndOrchestration#2]
As per Day 8, I first created a volume using #docker volume create volume_name
I'm getting Error: invalid container path "volume_name", must be an absolute path Error.

Please can you help to resolve this?

**Comment by AdminTurnedDevOps** [comment]
Hi,

Can you confirm that you went through the other 7 days and Docker is running? I just tried it and it's working. Screenshot below.

![2023-01-19_07-07-33](https://user-images.githubusercontent.com/28905827/213439176-dee37b31-ac3d-4761-a1e7-c5bfa1f17131.png)

**Comment by chetan-70** [comment]
Thanks. I was able to run on a fresh machine.
